<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNyu3eek\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNyu3eek/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerNyu3eek.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerNyu3eek\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerNyu3eek\appProdProjectContainer([
    'container.build_hash' => 'Nyu3eek',
    'container.build_id' => '66effab1',
    'container.build_time' => 1677690059,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNyu3eek');
