<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNyitet3\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNyitet3/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerNyitet3.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerNyitet3\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerNyitet3\appDevDebugProjectContainer([
    'container.build_hash' => 'Nyitet3',
    'container.build_id' => '90626571',
    'container.build_time' => 1677689986,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNyitet3');
